### PR TITLE
Bigdata

### PR DESCRIPTION
**Pull request by tlorans**
Hello,

I would like to propose the implementation of an algorithm in order to increase the speed of computation for large scale problem.
This is the implementation of the algorithm from Khezrimotlagh et al. 2019 : [https://www.sciencedirect.com/science/article/abs/pii/S0377221718309123](url). 

This is a first draft, and I still don't achieve to fully replicate your example results for a simple Radial model. 

Indeed, I have two issues here:
1. It's really hard to me to keep track of DMUs subsets without NamedArrays, could we add it as a depency and use it for this algorithm (NamedArrays are supported by JuMP)?;
2. In terms of results with "deabigdata" function, one of the DMU is still an exterior to the hull at the end of the process. I still can't figure out where does it comes from, but I'm pretty sure it's because I've lost track of DMUs subsets somewhere.

Also, I was wondering what would be the best approach: should I try to implement this as a separate model and separate file (ie. "bigdata.jl") or maybe integrate it in the dea.jl file directly and make it as an optional argument? What do you think?

Best regards,

Thomas

### CODE REVIEW

**Comment by javierbarbero** [comment]
Hello,

Thanks for this contribution. 
I will check the paper and the code to understand how the algorithm works.

1. I don't see a problem in adding NamedArrays as a dependency if it is necessary. I am not sure if it is compatible with JuMP. 

2. We should check this in detail, but the following lines cause problems as the rounding might generate projections that are outside the frontier by a little. This can cause problems in the second stage when solving the slacks.
```
effi = round.(effi ; digits = 6)
``` 

If we remove this line, it seems that the warnings are gone in the example. We have to check with more examples.

This should be definitely a new function. I like the `deabigdata` name you propose, or even `deabig`. 

Best,
Javier

**Comment by tlorans** [comment]
Hello,

1.  Just tried with NamedArrays. It didn't helped me to fix the issue regarding the exterior... So as long as it is not necessary, let's keep with the initial philosophy of the package (without NamedArrays), for consistency (otherwise we would need to switch between different types, which is not particularly efficient). 

2. I've dropped this line regard rounding, which can indeed be a source of mistake. I've also merged this current branch with the progressbarmeter one, as it could help us to get a sens of potential decrease in computing time between deabigdata and dea functions. 

EDIT: I've found the issue and now **deabigdata can replicate the efficiency scores resulting from the dea function**. 
The problem was in the bestpracticesfinder function: I identified best practices as those with efficiency score equal to one. But, actually we have some DMUs in the hull with efficiency scores such as 0.9999999999. Changing the conditional loop accordingly, the algorithm works.
I still have to treat the question regarding slacks: I should take slacks from previous computations (as for efficiency scores and lambdas) rather than running a new deadd. Will treat it in the coming days.

Best regards,

Thomas

**Comment by tlorans** [comment]
Hello,

I'm pleased to announce you that now the deabigdata function can replicates the dea function results. 
Could be interesting to benchmark both with large datasets.

Please let me know if you have some questions or suggestions.

Best regards,

Thomas

**Comment by javierbarbero** [comment]
Hi,

Thanks. This is going better!

I have made a commit with some bug fixed and code simplification. 
- Simplify code to select DMU's with the minimum input or the maximum output.
- Fix best practicers and exteriors selection for output oriented models.
- Allow for ```slacks = false```.
- Add default LP optimizer.

I have included a file with unit tests to test the function.

There are still some test that do not pass. 
Running the model with the example data:
```julia
X = [5 13; 16 12; 16 26; 17 15; 18 14; 23 6; 25 10; 27 22; 37 14; 42 25; 5 17]
Y = [12; 14; 25; 26; 8; 9; 27; 30; 31; 26; 12]
deaio = deabigdata(X, Y, orient = :Input, rts = :CRS)
deaio.lambda
```

The peers sparse matrix is a 11x4 matrix, instead of a 11x11 matrix:
```
11×4 SparseMatrixCSC{Float64, Int64} with 17 stored entries:
 1.0   ⋅         ⋅            ⋅ 
  ⋅    ⋅        0.333333      ⋅ 
  ⋅    ⋅        1.14815       ⋅ 
  ⋅   1.0       1.48479e-16   ⋅ 
 ⋮                           
  ⋅   0.257381  0.0484481     ⋅ 
  ⋅   1.03487   0.114574      ⋅ 
  ⋅   0.490566  0.490566      ⋅ 
```

We should update the code to include the remaining columns with zeros.

Best,
Javier

**Comment by tlorans** [comment]
Hi, 

Thank you for all this work!

I just fixed the issue regarding the Lambda sparse matrix. 

Regarding the implementation, I will try to take a look this week in order to simplify it and make it more coherent with the rest of the functions in the package:
1. I created a Type Subset in order to keep track of the index for each subsamples while I could have used SparseArrays or even simple matrix, such as recommended here [https://discourse.julialang.org/t/best-way-to-store-subsets-of-a-sample/68018/4](url);
2. If I undestand well, the structure of each function in the package are actually such as: a struct for the model type is defined, with parameters and results to be stored, and a function. As the KZCT algorithm is not a model, I should not create such a Type. Indeed, creating a Type like this would in fact make the module less flexible for potential extension (and potential use for multiple dispatch);
3. I've created too much functions to perform the algorithm, while the other functions embed all the different steps. As the algorithm is not particularly hard to understand or follow (it is but only due to my current poor implementation), I suggest to follow the same process than you did for the other function.





Best regards,

Thomas

**Comment by tlorans** [comment]
Hi, 

Just pushed a new version following my previous comment. Now we just have a function for the initial subsetting, the deabigdata function itself, and two technical functions to avoid to repeat some steps. 

Doing so, the deabigdata.jl script is two time less verbose than the previous version.

Hope we're better now :).

Best regards,

Thomas

**Comment by javierbarbero** [comment]
Thanks for your comments and the changes to the code.

This is much better and the code is easier to understand (I like that users can look at the code and understand what is going on).

It seems there is a problem when using the GLPK optimizer, but everything works fine with COSMO. I am going to look at it. I think this could be because for some variables GLPK returns a 0 while COSMO returns a value very close to 0, but not exactly zero.
```
julia> deabigdata(X, Y, orient = :Input, rts = :CRS, optimizer = DEAOptimizer(GLPK.Optimizer))
ERROR: ArgumentError: the first three arguments' lengths must match, length(I) (=44) == length(J) (= 44) == length(V) (= 17)
Stacktrace:
 [1] sparse(I::Vector{Int64}, J::Vector{Int64}, V::Vector{Float64}, m::Int64, n::Int64, combine::Function)
   @ SparseArrays /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/SparseArrays/src/sparsematrix.jl:736
 [2] sparse(I::Vector{Int64}, J::Vector{Float64}, V::Vector{Float64}, m::Int64, n::Int64, combine::Function)
   @ SparseArrays /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/SparseArrays/src/sparsematrix.jl:773
 [3] sparse(I::Vector{Int64}, J::Vector{Float64}, V::Vector{Float64}, m::Int64, n::Int64)
   @ SparseArrays /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/SparseArrays/src/sparsematrix.jl:956
 [4] deabigdata(X::Matrix{Int64}, Y::Vector{Int64}; orient::Symbol, rts::Symbol, slack::Bool, disposX::Symbol, disposY::Symbol, names::Nothing, optimizer::DEAOptimizer)
   @ DataEnvelopmentAnalysis ~/Documents/GitHub/DataEnvelopmentAnalysis.jl/src/deabigdata.jl:302
 [5] top-level scope
   @ REPL[32]:1
```

I will check how we can fix this.

Best,
Javier

**Comment by tlorans** [comment]
Hi Javier,

Thank your for your check.

Regarding the sparse array, maybe a solution could be to store the intermediate results as a Matrix (to store the zeros as well) and building the sparse matrix at the end only with a `sparse(Matrixresults)`?  Not really sure if it could works.

Unfortunately I can't immediately reproduce the error as I can't use GLPK...Maybe I could find an access to another computer this week. I'll let you know!

Best regards,

Thomas

**Comment by tlorans** [comment]
Hi Javier,

Thank you again for your help. I think we are quite okay now :).

Best regards,

Thomas

**Comment by javierbarbero** [comment]
Hi Thomas,

I have made some changes to the code to increase the speed of the algorithm and reduce the memory allocations:
- Calculate all the quantiles simultaneously instead of calling the `quantile!` function 100 times.
- `Dˢ`, `D_excluding_Dˢ`, and others are now vectors of the DMU numbers in the subset and not a matrix with the subset of DMU's numbers with their inputs and outputs. This reduces memory allocation.
- Results are not stores in a `results` matrix. They are kept in the DEA output structures and retrieved if and when needed. 

With this example:
```julia
rng = StableRNG(1234567)
X = rand(Uniform(10, 20), 1000, 5)
Y = rand(Uniform(10, 20), 1000, 5)
@btime rdeabig = deabigdata(X, Y, progress = false);
```

time and memory allocation changed from:
```
15.851 s (75414678 allocations: 12.20 GiB)
```

to 
```
4.202 s (39139312 allocations: 2.55 GiB)
```

I have also added a couple of unit tests, including a test with 500 random DMU's. All tests are successful. :)

I will work on updating the documentation, and we will be ready to merge.

Best,
Javier

**Comment by tlorans** [comment]
Hi Javier,

Thank you for these improvements!

Yes, my scripting is still really weak regarding the issue of memory allocation…then thank you for this really good example of impressive performance improvement with such strategies. 

More generally, I’m reading the book
« Hands-On Design Patterns and Best Practices with Julia: Proven solutions to common problems in software design for Julia 1.x ». I hope my future commits will be of better quality in the coming weeks :).

Best regards,

Thomas

**Comment by javierbarbero** [comment]
Done. I have merged this pull request with the main branch.

Many thanks for your contribution.

Best,
Javier

**Pull request merged**
