### PR TITLE
add progress meter for simple radial model

### PR DESCRIPTION
**Pull request by tlorans**
Hello,

Please see a new version for the progress meter feature.
I've added a file "progressbarmeter.jl" defining the function, and implement it for the simple radial model as a first step.

Let me know if this is better for you. In that case I could try to implement it for other models.

Best regards,

Thomas

### CODE REVIEW

**Comment by javierbarbero** [comment]
Hi,

This is great! Thanks.
I have made a commit with some changes.
- Add compat entry to Project.toml
- Change `show_progress` to `progress`.
- Add `desc` parameter for descriptive text.
- Update test to run both with and without progress meter.

What do you thing?
If this is OK, I can merge this PR.

Best,
Javier

**Comment by tlorans** [comment]
Hi, 
It's really nice, especially to get some more precise descriptive text during the model processing. That's all good to me!
So you merge this PR and then I'll try to expand this feature to the other model?

Best regards,

Thomas

**Comment by javierbarbero** [comment]
Done! :)
If you have time would be nice if you can expand this to the other models.

**Comment by tlorans** [comment]
> Done! :)
> If you have time would be nice if you can expand this to the other models.

Yep, I'll take a look in the coming days.

**Pull request merged**
